services:
  mariadb:
    image: mariadb:11
    container_name: cycling-mariadb
    restart: unless-stopped

    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"

    volumes:
      - /srv/cycling/data/mariadb:/var/lib/mysql

    ports:
      - "${MARIADB_PORT}:3306"