#!/usr/bin/env bash
set -euo pipefail
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" LANG=C.UTF-8 LC_ALL=C.UTF-8
umask 077
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"; PLATFORM_DIR="${PLATFORM_DIR:-/home/tim/cycling-platform}"; COMPOSE="${COMPOSE_WRAPPER:-$SCRIPT_DIR/compose.sh}"
OUTPUT=""; SET=""; RESTORE_AT=""; RUNTIME=""; STATIC=""; DEPLOY=""; BOOTSTRAP=""; CATCHUP=""; VALIDATION=""; DAILY=""; OPERATIONS=""; DURATION=""; DEBT="none"
fail(){ printf '[recovery-acceptance] ERROR: %s\n' "$*" >&2; exit 1; }
while (( $# )); do case "$1" in --output) OUTPUT="${2:-}"; shift 2;; --backup-set) SET="${2:-}"; shift 2;; --restore-completed-at) RESTORE_AT="${2:-}"; shift 2;; --runtime-credentials) RUNTIME="${2:-}"; shift 2;; --static-config) STATIC="${2:-}"; shift 2;; --deployment-ready) DEPLOY="${2:-}"; shift 2;; --bootstrap-migration) BOOTSTRAP="${2:-}"; shift 2;; --catch-up) CATCHUP="${2:-}"; shift 2;; --publication-validation) VALIDATION="${2:-}"; shift 2;; --daily-result) DAILY="${2:-}"; shift 2;; --operational-checks) OPERATIONS="${2:-}"; shift 2;; --daily-duration-seconds) DURATION="${2:-}"; shift 2;; --technical-debt) DEBT="${2:-}"; shift 2;; -h|--help) echo 'Usage: record_recovery_acceptance.sh --output FILE --backup-set PREFIX --restore-completed-at ISO_TIME --runtime-credentials passed --static-config passed --deployment-ready passed --bootstrap-migration passed --catch-up passed --publication-validation passed --daily-result passed --operational-checks passed --daily-duration-seconds N [--technical-debt TEXT]'; exit 0;; *) fail "Unknown argument: $1";; esac; done
[[ "$OUTPUT" =~ ^/[A-Za-z0-9._/-]+$ ]] || fail 'Output must be a safe absolute path.'; [[ "$SET" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{6}$ ]] || fail 'Backup set prefix is invalid.'; [[ "$RESTORE_AT" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T ]] || fail 'Restore completion time must be ISO-like.'; [[ "$DURATION" =~ ^[0-9]+$ ]] || fail 'Daily duration must be numeric.'
for result in "$RUNTIME" "$STATIC" "$DEPLOY" "$BOOTSTRAP" "$CATCHUP" "$VALIDATION" "$DAILY" "$OPERATIONS"; do [[ "$result" == passed ]] || fail 'All acceptance result flags must be passed.'; done
static_config="${STATIC_CONFIG_PATH:-$ROOT/compose/.env}"; runtime="${RUNTIME_RENVIRON:-/srv/cycling/config/platform/runtime.Renviron}"
"$SCRIPT_DIR/verify_static_config.sh" --plaintext "$static_config" >/dev/null
[[ "$(stat -c '%U:%G %a' "$runtime")" == 'tim:tim 600' ]] || fail 'Runtime credential metadata is not canonical.'
for lock in /tmp/cycling-platform-daily.lock /tmp/cycling-platform-validation.lock /tmp/cycling-platform-deployment.lock /tmp/cycling-platform-database-restore.lock; do [[ ! -d "$lock" ]] || fail "Managed lock remains: $lock"; done
mariadb_id="$($COMPOSE ps -q mariadb)"; [[ -n "$mariadb_id" ]] || fail 'MariaDB is not running.'; health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$mariadb_id")"; [[ "$health" == healthy ]] || fail "MariaDB is not healthy: $health"
platform_running="$($COMPOSE ps -q cycling-platform)"; [[ -z "$platform_running" ]] || fail 'A platform job remains running.'
host="$(hostname -s)"; cron_state=disabled; if crontab -l 2>/dev/null | grep -Fq '# >>> CYCLING_PLATFORM_START >>>'; then cron_state=enabled; fi
[[ "$host" == cycling-prod || "$cron_state" == disabled ]] || fail 'Production scheduling must remain disabled on an isolated recovery host.'
infra_sha="$(git -C "$ROOT" rev-parse HEAD)"; platform_sha="$(git -C "$PLATFORM_DIR" rev-parse HEAD)"; image_ref="$($COMPOSE config --images | awk '/^cycling-platform:/ {print; exit}')"; image_id="$(docker image inspect --format '{{.Id}}' "$image_ref")"
outdir="$(dirname "$OUTPUT")"; [[ -d "$outdir" && -w "$outdir" ]] || fail 'Evidence output directory is unavailable.'; tmp="${OUTPUT}.tmp.$$"; trap 'rm -f -- "$tmp"' EXIT
printf 'format=cycling-recovery-acceptance-v2\nrecorded_at_utc=%s\nrecovery_host=%s\nbackup_set=%s\ndatabase_restore_result=passed\ndatabase_restore_completed_at=%s\nstatic_config_verification=passed\nruntime_credential_verification=passed\ninfrastructure_commit=%s\nplatform_commit=%s\nimage_id=%s\ndeployment_ready=passed\nbootstrap_migration_result=passed\nrestored_state_publication_validation=passed\nprovider_catch_up_result=passed\nfinal_daily_result=passed\nfinal_daily_duration_seconds=%s\noperational_checks_result=passed\nruntime_credential_metadata=tim:tim-0600\nmariadb_health=healthy\nproduction_schedule=%s\nmanaged_locks=clear\nplatform_containers=none\naccepted_technical_debt=%s\ndr_acceptance=passed\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$host" "$SET" "$RESTORE_AT" "$infra_sha" "$platform_sha" "$image_id" "$DURATION" "$cron_state" "$(printf '%s' "$DEBT" | tr '\n=' '  ')" >"$tmp"
chmod 600 "$tmp"; mv -f -- "$tmp" "$OUTPUT"; trap - EXIT; printf '[recovery-acceptance] Acceptance evidence recorded: %s\n' "$OUTPUT"
